<!-- https://www.displayr.com/formattable/ -->
<!-- https://cran.r-project.org/web/packages/formattable/formattable.pdf -->
```{r}
library(formattable)
library(tidyverse)
```

```{r}
p <- percent(x = c(0.04, 0.05), digits = 2)
max(p)
p + 0.01
```


```{r}

df <- data.frame(
    id = 1:10,
    name = c("Bob", "Ashley", "James", "David", "Jenny", 
             "Hans", "Leo", "John", "Emily", "Lee"), 
    age = c(28, 27, 30, 28, 29, 29, 27, 27, 31, 30),
    grade = c("C", "A", "A", "C", "B", "B", "B", "A", "C", "C"),
    test1_score = c(8.9, 9.5, 9.6, 8.9, 9.1, 9.3, 9.3, 9.9, 8.5, 8.6),
    test2_score = c(9.1, 9.1, 9.2, 9.1, 8.9, 8.5, 9.2, 9.3, 9.1, 8.8),
    final_score = c(9, 9.3, 9.4, 9, 9, 8.9, 9.25, 9.6, 8.8, 8.7),
    registered = c(TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE),
    stringsAsFactors = FALSE)

formattable(x = df, 
            align = c(rep("l", 2), rep("c", 2), rep("r", 2), rep("c", 2)),
            list(
                age = color_tile("white", "orange"),
                grade = formatter(
                    .tag = "span", 
                    style = x ~ case_when(
                        x == "A" ~ style(color = "green", font.weight = "bold"),
                        x == "B" ~ style(color = "blue", font.weight = "normal"),
                        x == "C" ~ style(color = "orange", font.style = "italic")
                    )
                ),
                area(col = c(test1_score, test2_score)) ~ normalize_bar(color = "teal", 0.25),
                final_score = formatter(
                    .tag = "span",
                    style = x ~ style(color = ifelse(rank(-x) <= 3, "green", "gray"), text.color = "white"),
                    x ~ sprintf(fmt = "%.2f (rank: %02d)", x, rank(-x))
                ),
                registered = formatter(
                    .tag = "span",
                    style = x ~ style(color = ifelse(x, "green", "red")),
                    x ~ icontext(icon = ifelse(x, "ok", "remove"), text = ifelse(x, "Yes", "No"))
                )
            )
)
```


